config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  # resources :items, only: [:index, :show]

  get 'items', to: 'items#index'
  get 'items/:id', to: 'items#show', as: 'item'

  # resources :orders, only: [:create]

  get 'orders', to: 'orders#index'
  post 'orders', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  # resources :users, only: [:new, :create, :edit, :update]
  post 'users', to: 'users#create'
  get 'users/new', to: 'users#new', as: 'new_user'
  get 'users/:id/edit', to: 'users#edit', as: "edit_user"
  patch 'users/:id', to: 'users#update', as: "user"

  get '/dashboard', to: 'users#show'

  namespace :admin do
    get 'dashboard', to: 'users#show', as: 'dashboard'
    get 'dashboard/edit', to: 'users#edit', as: 'edit_dashboard'
    patch 'dashboard', to: 'users#update'
    patch 'dashboard/orders', to: 'orders#update', as: 'edit_order_status'
    get 'dashboard/items', to: 'items#index', as: 'items'
    get 'dashboard/items/:id/edit', to: 'items#edit', as: 'edit_item'
    patch 'dashboard/items/:id', to: 'items#update', as: 'update_item'
    get 'dashboard/:status', to: 'orders#index', as: 'orders'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/cart", to: "cart#show"
  post "/cart", to: "cart#create"
  patch "/cart", to: "cart#update"
  delete "/cart", to: "cart#destroy"


  get "/:category_name", to: "categories#show", as: "category"

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents = nil)
    @contents = contents || {}
  end

  def add_item(item_id)
    contents[item_id.to_s] ||= 0
    contents[item_id.to_s] += 1
  end

  def quantity(item_id)
    contents[item_id.to_s]
  end

  def item_subtotal(item_id)
    Item.find(item_id).price * quantity(item_id)
  end

  def total_price
    items = Item.where(id: contents.keys)
    items.reduce(0) { |sub_total, item| sub_total + item.price * quantity(item.id) }
  end

  def clear
    @contents = {}
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ActionView::Helpers::TextHelper
    before_action :current_item, only: [:create, :destroy]

  def create
    @cart.add_item(@current_item.id)
    update_cart
    redirect_back(fallback_location: items_path)
  end

  def show
    @items = Item.where(id: @cart.contents.keys)
  end

  def update
    @cart.contents[params[:cart][:item_id]] = params[:cart][:quantity].to_i
    update_cart

    redirect_back(fallback_location: items_path)
  end

  def destroy
    @cart.contents.delete(params[:item_id])
    update_cart

    flash[:success] = "Successfully removed #{view_context.link_to(@current_item.title, item_path(@current_item))} from your cart."

    redirect_back(fallback_location: items_path)
  end

  private

  def current_item
    @current_item = Item.find(params[:item_id])
  end
end

app/views/cart/_full_cart_display.html.erb
<% if cart_full? %>
  <div class="row text-right well">
    <h3>Total: <%= cents_to_dollar @cart.total_price %></h3>
    <% if current_user %>
      <%= button_to "Checkout", orders_path, class: "btn btn-primary btn-lg" %>
    <% else %>
      <p>
        <%= link_to "Login", login_path, id: "checkout-login" %>
        or
        <%= link_to "Create Account", new_user_path %>
        to Checkout
      </p>
    <% end %>
  </div>
<% else %>
  <div class="row text-center well">
    <p>Your cart is empty.</p>
    <p><%= link_to "Start shopping!", items_path %></p>
  </div>
<% end %>

app/views/cart/show.html.erb
<div class="container" style="margin-top:50px;margin-bottom:100px;">
  <% @items.each do |item| %>
  <div class ="row">
    <div class="col-md-4">
      <img src="<%= item.image_path %>" alt="Item" class="img-responsive">
    </div>

    <div class="col-md-8" style="margin-bottom:20px;">
      <h3><%= item.title %></h3>
      <p>Description: <%=item.description%></p>
      <p>Price: <%= cents_to_dollar item.price %></p>
      <p>Subtotal: <%= cents_to_dollar @cart.item_subtotal(item.id) %></p>
      <p>
        <%= form_for :cart, method: :patch do |f| %>
          <%= f.hidden_field :item_id, value: item.id %>
          <%= f.label :quantity %>
          <%= f.number_field :quantity, value: @cart.quantity(item.id), min: 1 %>
          <%= f.submit "Update", class: 'btn btn-outline-secondary' %>
        <% end %>
      </p>
      <%= button_to "Remove", cart_path(item_id: item.id), method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
  <% end %>

  <div class="container" style="margin-top:100px;margin-bottom:100px;">
    <%= render partial: 'full_cart_display' %>
  </div>
</div>