config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  # resources :items, only: [:index, :show]

  get 'items', to: 'items#index'
  get 'items/:id', to: 'items#show', as: 'item'

  # resources :orders, only: [:create]

  get 'orders', to: 'orders#index'
  post 'orders', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  # resources :users, only: [:new, :create, :edit, :update]
  post 'users', to: 'users#create'
  get 'users/new', to: 'users#new', as: 'new_user'
  get 'users/:id/edit', to: 'users#edit', as: "edit_user"
  patch 'users/:id', to: 'users#update', as: "user"

  get '/dashboard', to: 'users#show'

  namespace :admin do
    get 'dashboard', to: 'users#show', as: 'dashboard'
    get 'dashboard/edit', to: 'users#edit', as: 'edit_dashboard'
    patch 'dashboard', to: 'users#update'
    patch 'dashboard/orders', to: 'orders#update', as: 'edit_order_status'
    get 'dashboard/items', to: 'items#index', as: 'items'
    get 'dashboard/items/:id/edit', to: 'items#edit', as: 'edit_item'
    patch 'dashboard/items/:id', to: 'items#update', as: 'update_item'
    get 'dashboard/:status', to: 'orders#index', as: 'orders'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/cart", to: "cart#show"
  post "/cart", to: "cart#create"
  patch "/cart", to: "cart#update"
  delete "/cart", to: "cart#destroy"


  get "/:category_name", to: "categories#show", as: "category"

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
                       uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  has_secure_password

  has_many :orders
  has_many :ordered_items, through: :orders
  has_many :items, through: :ordered_items

  enum role: %w(default admin)

  def item_recommender
    @item_recommender ||= ItemRecommender.new(self)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    def show
      @user = current_user
      @orders = Order.all.order(created_at: :desc)
    end

    def edit
      @user = current_user
    end

    def update
      @user = current_user
      if @user.update(user_params)
        redirect_to admin_dashboard_path
      else
        flash.now[:warning] = "Please make sure fields are updated correctly"
        render :edit
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to "/dashboard"
    else
      flash[:danger] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      flash.now[:warning] = "Please make sure fields are updated correctly"
      render :edit
    end
  end
end

app/views/users/edit.html.erb
<div class="container" style="margin-top:50px;margin-bottom:100px;">
  <div class="page-header">
    <h1><%= @user.username%>'s Profile Page</h1>
  </div>

  <%= render partial: "shared/edit_profile_form.html", locals: {user_path: user_path} %>
</div>

app/views/users/new.html.erb
<<div class="container" style="margin-top:50px;margin-bottom:100px;">
  <div class="container-fluid well well-lg">
    <%= form_for(@user) do |f| %>
      <div class="form-group row">
        <%= f.label :first_name, class: "col-xs-2 col-form-label" %>
        <div class="col-xs-10">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :last_name, class: "col-xs-2 col-form-label" %>
        <div class="col-xs-10">
          <%= f.text_field :last_name, class: "form-control" %><br>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :username, class: "col-xs-2 col-form-label" %>
          <div class="col-xs-10">
            <%= f.text_field :username, class: "form-control" %><br>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :street_address, class: "col-xs-2 col-form-label" %>
          <div class="col-xs-10">
            <%= f.text_field :street_address, class: "form-control" %><br>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :city, class: "col-xs-2 col-form-label" %>
          <div class="col-xs-10">
            <%= f.text_field :city, class: "form-control" %>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :state, class: "col-xs-2 col-form-label"  %>
          <div class="col-xs-10">
            <%= render partial: "shared/state_dropdown" %><br />
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :zip_code, class: "col-xs-2 col-form-label"  %>
          <div class="col-xs-10">
            <%= f.text_field :zip_code, class: "form-control" %><br>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :password, class: "col-xs-2 col-form-label"  %>
          <div class="col-xs-10">
            <%= f.password_field :password, class: "form-control" %><br>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :password_confirmation, class: "col-xs-2 col-form-label"  %>
          <div class="col-xs-10">
            <%= f.password_field :password_confirmation, class: "form-control" %><br>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :gender, class: "col-xs-2 col-form-label"  %>
          <div class="col-xs-10">
            <%= f.select(:gender, options_for_select([['Female', 'Female'], ['Male', 'Male'], ['Transgender', 'Transgender'], ['Other', 'Other'], ['Prefer Not To Say', 'Prefer Not To Say']], 1)) %><br>
          </div>
      </div>

      <%= f.submit "Register", class: "btn btn-primary btn-lg btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" style="margin-top:50px;margin-bottom:200px;">
  <div class="container">

    <div class="page-header">
      <h1><%= current_user.username.capitalize %>'s Dashboard</h1>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= image_tag current_user.user_image, class: "img-responsive", style: "margin-bottom:20px;" %>
      </div>
      <div class="col-md-8">

        <p><%= formatted_name(current_user) %></p><br>

        <p><%= formatted_address(current_user) %></p><br>

        <p><%= current_user.gender %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <%= button_to "Edit Profile", edit_user_path(current_user), method: :get, class: "btn btn-info btn-lg" %>

        <%= button_to "View Past Orders", orders_path, method: :get, class: "btn btn-success btn-lg" %>
      </div>
    </div>

  </div>
  <div class="row">
    <h3 class="text-center"><u>Your Top Items</u></h4>
    <% current_user.item_recommender.top_user_items.each do |item| %>
    <%= render partial: "shared/item_container", locals: { item: item } %>
    <% end %>
  </div>
</div>