config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  # resources :items, only: [:index, :show]

  get 'items', to: 'items#index'
  get 'items/:id', to: 'items#show', as: 'item'

  # resources :orders, only: [:create]

  get 'orders', to: 'orders#index'
  post 'orders', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  # resources :users, only: [:new, :create, :edit, :update]
  post 'users', to: 'users#create'
  get 'users/new', to: 'users#new', as: 'new_user'
  get 'users/:id/edit', to: 'users#edit', as: "edit_user"
  patch 'users/:id', to: 'users#update', as: "user"

  get '/dashboard', to: 'users#show'

  namespace :admin do
    get 'dashboard', to: 'users#show', as: 'dashboard'
    get 'dashboard/edit', to: 'users#edit', as: 'edit_dashboard'
    patch 'dashboard', to: 'users#update'
    patch 'dashboard/orders', to: 'orders#update', as: 'edit_order_status'
    get 'dashboard/items', to: 'items#index', as: 'items'
    get 'dashboard/items/:id/edit', to: 'items#edit', as: 'edit_item'
    patch 'dashboard/items/:id', to: 'items#update', as: 'update_item'
    get 'dashboard/:status', to: 'orders#index', as: 'orders'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/cart", to: "cart#show"
  post "/cart", to: "cart#create"
  patch "/cart", to: "cart#update"
  delete "/cart", to: "cart#destroy"


  get "/:category_name", to: "categories#show", as: "category"

end

app/views/shared/_edit_profile_form.html.erb
<div class="container-fluid">
  <%= form_for(@user, url: user_path) do |f| %>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control"%><br>
    </div>

    <div class="form-group">
      <%= f.label :street_address %>
      <%= f.text_field :street_address, class: "form-control"%><br>
    </div>

    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :state %>
      <%= render partial: "shared/state_dropdown", class: "form-control"%><br>
    </div>

    <div class="form-group">
      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: "form-control"%><br>
    </div>

    <div class="form-group">
      <%= f.label :user_image %>
      <%= f.text_field :user_image, class: "form-control", type: "url" %><br>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %><br>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %><br>
    </div>

    <div class="form-group">
      <%= f.label :gender %>
      <%= f.select(:gender, options_for_select([['Female', 'Female'], ['Male', 'Male'], ['Transgender', 'Transgender'], ['Other', 'Other'], ['Prefer Not To Say', 'Prefer Not To Say']], 1)) %><br>
    </div>

    <%= f.submit "Update Information", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-6">
                    <h3>Location</h3>
                    <p>1510 Blake Street
                        <br>Denver, CO 80202</p>
                </div>
                <div class="footer-col col-md-6">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><p>Facebook</p></a>
                        </li>
                        <li>
                            <a href="#"><p>Twitter</p></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; GoodGrocers 2016
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_item_container.html.erb
<div class="container col-md-4">
  <div class="well">
    <div class="<%= item.title %> items-display-height">
      <a href="/items/<%= item.id %>">
        <h3><%= item.title %></h3>
        <%= image_tag item.image_path, class: "img-responsive" %>
      </a>
      <p><%= item.description %></p>
      <p><%= cents_to_dollar item.price %></p>

      <%= button_to "Add to Cart", cart_path(:item_id => item.id), class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= "/">GoodGrocer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="<%= items_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop <span class="caret"></span></a>
          <% if all_categories %>
            <ul class="dropdown-menu">
              <% all_categories.each do |category| %>
                <li><a href="/<%= category.slug %>"><%= category.name %></a></li>
              <% end %>
            </ul>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="logged-as-navbar">Logged in as</li>
          <li class="username-navbar"><%= link_to "#{current_user.username} |", path_based_on_role%></li>
          <li class="logout-as-navbar"><%= link_to "Logout |", logout_path %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
        <li><a href="<%= cart_path  %>" id="cart_link"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
        <li class="dropdown">
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_state_dropdown.html.erb
<select name="user[state]" id="user_city">
  <option value="Alabama">AL</option>
  <option value="Alaska">AK</option>
  <option value="Arizona">AZ</option>
  <option value="Arkansas">AR</option>
  <option value="California">CA</option>
  <option value="Colorado">CO</option>
  <option value="Connecticut">CT</option>
  <option value="Delaware">DE</option>
  <option value="Florida">FL</option>
  <option value="Georgia">GA</option>
  <option value="Hawaii">HI</option>
  <option value="Idaho">ID</option>
  <option value="Illinois">IL</option>
  <option value="Indiana">IN</option>
  <option value="Iowa">IA</option>
  <option value="Kansas">KS</option>
  <option value="Kentucky">KY</option>
  <option value="Louisiana">LA</option>
  <option value="Maine">ME</option>
  <option value="Maryland">MD</option>
  <option value="Massachusetts">MA</option>
  <option value="Michigan">MI</option>
  <option value="Minnesota">MN</option>
  <option value="Mississippi">MS</option>
  <option value="Missouri">MO</option>
  <option value="Montana">MT</option>
  <option value="Nebraska">NE</option>
  <option value="Nevada">NV</option>
  <option value="New Hampshire">NH</option>
  <option value="New Jersey">NJ</option>
  <option value="New Mexico">NM</option>
  <option value="New York">NY</option>
  <option value="North Carolina">NC</option>
  <option value="North Dakota">ND</option>
  <option value="Ohio">OH</option>
  <option value="Oklahoma">OK</option>
  <option value="Oregon">OR</option>
  <option value="Pennsylvania">PA</option>
  <option value="Rhode Island">RI</option>
  <option value="South Carolina">SC</option>
  <option value="South Dakota">SD</option>
  <option value="Tennessee">TN</option>
  <option value="Texas">TX</option>
  <option value="Utah">UT</option>
  <option value="Vermont">VT</option>
  <option value="Virginia">VA</option>
  <option value="Washington">WA</option>
  <option value="West Virginia">WV</option>
  <option value="Wisconsin">WI</option>
  <option value="Wyoming">WY</option>
</select>