config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  # resources :items, only: [:index, :show]

  get 'items', to: 'items#index'
  get 'items/:id', to: 'items#show', as: 'item'

  # resources :orders, only: [:create]

  get 'orders', to: 'orders#index'
  post 'orders', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  # resources :users, only: [:new, :create, :edit, :update]
  post 'users', to: 'users#create'
  get 'users/new', to: 'users#new', as: 'new_user'
  get 'users/:id/edit', to: 'users#edit', as: "edit_user"
  patch 'users/:id', to: 'users#update', as: "user"

  get '/dashboard', to: 'users#show'

  namespace :admin do
    get 'dashboard', to: 'users#show', as: 'dashboard'
    get 'dashboard/edit', to: 'users#edit', as: 'edit_dashboard'
    patch 'dashboard', to: 'users#update'
    patch 'dashboard/orders', to: 'orders#update', as: 'edit_order_status'
    get 'dashboard/items', to: 'items#index', as: 'items'
    get 'dashboard/items/:id/edit', to: 'items#edit', as: 'edit_item'
    patch 'dashboard/items/:id', to: 'items#update', as: 'update_item'
    get 'dashboard/:status', to: 'orders#index', as: 'orders'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/cart", to: "cart#show"
  post "/cart", to: "cart#create"
  patch "/cart", to: "cart#update"
  delete "/cart", to: "cart#destroy"


  get "/:category_name", to: "categories#show", as: "category"

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
                       uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  has_secure_password

  has_many :orders
  has_many :ordered_items, through: :orders
  has_many :items, through: :ordered_items

  enum role: %w(default admin)

  def item_recommender
    @item_recommender ||= ItemRecommender.new(self)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    def show
      @user = current_user
      @orders = Order.all.order(created_at: :desc)
    end

    def edit
      @user = current_user
    end

    def update
      @user = current_user
      if @user.update(user_params)
        redirect_to admin_dashboard_path
      else
        flash.now[:warning] = "Please make sure fields are updated correctly"
        render :edit
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to "/dashboard"
    else
      flash[:danger] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      flash.now[:warning] = "Please make sure fields are updated correctly"
      render :edit
    end
  end
end

app/views/admin/users/_order_table.html.erb
<table class="table">
  <thead>
    <tr>
      <td>Order #</td>
      <td>Status</td>
      <td>Action</td>
    </tr>

  </thead>
  <tbody>
    <% orders.each do |order| %>
    <tr>
      <td> <%= link_to "##{order.id}", order %></td>
      <td> <%= order.status %> </td>
      <td>
          <% if order.status =='Ordered' %>
            <%= link_to "Mark As Paid", admin_edit_order_status_path(status: "Paid", order_id: order.id), method: :patch %> |
          <% end %>

          <% if order.status =='Paid' %>
            <%= link_to "Mark As Completed", admin_edit_order_status_path(status: "Completed", order_id: order.id), method: :patch %> |
          <% end %>

          <% if order.status == 'Paid' || order.status == 'Ordered' %>
            <%= link_to "Cancel", admin_edit_order_status_path(status: "Cancelled", order_id: order.id), method: :patch  %>
          <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/edit.html.erb
<div class="container" style="margin-top:50px;margin-bottom:100px;">
  <div class="container">
    <div class="page-header">
      <h1><%= @user.username%>'s Profile Page</h1>
    </div>

    <%= render partial: "shared/edit_profile_form.html", locals: {user_path: admin_dashboard_path} %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container" style="margin-top:50px;margin-bottom:200px;">
  <div class="container">

    <ol class="breadcrumb">
      <li class="active">Dashboard</a></li>
    </ol>

    <div class="page-header">
      <h1>Admin Dashboard</h1>
    </div>

  <div class="container">
    <p>Profile Image:</p> <%=image_tag @user.user_image, class: "img-thumbnail", style: "margin-bottom:20px;" %><br>
    <p><%= formatted_name(@user) %></p><br>

    <p><%= formatted_address(@user) %></p><br>

    <p><%= @user.gender %></p>
  </div>

  <%= button_to "Update Profile", admin_edit_dashboard_path, method: :get, class: "btn btn-success btn-lg" %><br>
  <%= button_to "View All Items", admin_items_path, method: :get, class: "btn btn-primary btn-lg" %><br>

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= button_to "Open Orders", '/admin/dashboard/ordered', method: :get, class: "btn btn-info" %>
      </div>

      <div class="col-md-3">
        <%= button_to "Paid Orders", '/admin/dashboard/paid', method: :get, class: "btn btn-info" %>
      </div>

      <div class="col-md-3">
        <%= button_to "Completed Orders", '/admin/dashboard/completed', method: :get, class: "btn btn-info" %>
      </div>

      <div class="col-md-3">
        <%= button_to "Cancelled Orders", '/admin/dashboard/cancelled', method: :get, class: "btn btn-info" %>
      </div>
    </div>
  </div>

  <%= render partial: "order_table", locals: { orders: @orders } %>
</div>
</div>